# Generated by Django 5.0.6 on 2024-06-14 17:16

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                default=users.models.username_generator,
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
    ]
