# Generated by Django 5.0.6 on 2024-06-22 09:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_user_is_active"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ("-created_at",)},
        ),
    ]
