# fly.toml app configuration file generated for majibu-app-dev on 2024-07-05T19:06:10+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'majibu-app-dev'
primary_region = 'jnb'
kill_signal = 'SIGINT'
kill_timeout = '10s'

[build]
  dockerfile = 'docker/Dockerfile'

[env]
  DJANGO_SETTINGS_MODULE = 'majibu.settings'

[[services]]
  protocol = 'tcp'
  internal_port = 8000
  processes = ['app']

  [[services.ports]]
    port = 80
    handlers = ['http']
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [services.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = '15s'
    timeout = '2s'
    grace_period = '1s'

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = '/app/static'
  url_prefix = '/static'

[processes]
  app = ""
  celery_worker = "celery -A majibu worker -l info"
  celery_beat = "celery -A majibu beat -l info"
