# Generated by Django 5.0.6 on 2024-06-22 10:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MpesaPayments",
            new_name="MpesaPayment",
        ),
        migrations.RenameModel(
            old_name="Withdrawals",
            new_name="Withdrawal",
        ),
    ]
