# Generated by Django 5.0.6 on 2024-08-01 11:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_transaction_charge"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mpesapayment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="withdrawal",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
