version: "3.9"

services:

  app:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    image: majibu
    networks:
      - majibu-backend-network
    container_name: majibu-api
    restart: always
    volumes:
      - .:/majibu
    ports:
      - "8000:8000"

  celery_worker:
    container_name: celery-worker
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    networks:
      - majibu-backend-network
    command: celery -A majibu worker -l info
    volumes:
      - .:/majibu
    depends_on:
      - app

  celery_beat:
    container_name: celery-beat
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    networks:
      - majibu-backend-network
    command: celery -A majibu.celery  -l info
    volumes:
      - .:/majibu
    depends_on:
      - app

volumes:
  db_data:

networks:
  majibu-backend-network:
    name: majibu-backend-network
