# Generated by Django 5.0.6 on 2024-07-25 15:47

import django.db.models.deletion
import user_sessions.constants
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_sessions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DuoSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("party_a", models.CharField(max_length=255)),
                ("party_b", models.CharField(max_length=255, null=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="This is the Amount that was transacted.",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            (
                                user_sessions.constants.DuoSessionStatuses["PAIRED"],
                                "PAIRED",
                            ),
                            (
                                user_sessions.constants.DuoSessionStatuses["REFUNDED"],
                                "REFUNDED",
                            ),
                            (
                                user_sessions.constants.DuoSessionStatuses[
                                    "PARTIALLY_REFUNDED"
                                ],
                                "PARTIALLY_REFUNDED",
                            ),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                ("winner_id", models.CharField(max_length=255, null=True)),
                (
                    "session",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="user_sessions.session",
                    ),
                ),
            ],
        ),
    ]
