# Generated by Django 5.0.6 on 2024-07-24 22:56

import commons.constants
import user_sessions.constants
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_sessions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="duosession",
            name="status",
            field=models.CharField(
                choices=[
                    (user_sessions.constants.DuoSessionStatuses["PAIRED"], "PAIRED"),
                    (
                        user_sessions.constants.DuoSessionStatuses["REFUNDED"],
                        "REFUNDED",
                    ),
                    (
                        user_sessions.constants.DuoSessionStatuses[
                            "PARTIALLY_REFUNDED"
                        ],
                        "PARTIALLY_REFUNDED",
                    ),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="sessions",
            name="category",
            field=models.CharField(
                choices=[
                    (commons.constants.SessionCategories["FOOTBALL"], "FOOTBALL"),
                    (commons.constants.SessionCategories["BIBLE"], "BIBLE"),
                ],
                max_length=255,
            ),
        ),
    ]
