# Generated by Django 5.0.6 on 2024-07-30 11:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "user_sessions",
            "0002_alter_duosession_party_a_alter_duosession_party_b_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="duosession",
            old_name="winner_id",
            new_name="winner",
        ),
    ]
