# Generated by Django 5.0.6 on 2024-08-01 11:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_sessions", "0003_rename_winner_id_duosession_winner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="duosession",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="poolsessionstat",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="session",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="usersessionstat",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
