# Generated by Django 5.0.6 on 2024-07-18 01:57

import django.db.models.deletion
import notifications.constants
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            (notifications.constants.NotificationTypes["OTP"], "OTP"),
                            (
                                notifications.constants.NotificationTypes["MARKETING"],
                                "MARKETING",
                            ),
                            (
                                notifications.constants.NotificationTypes["DEPOSIT"],
                                "DEPOSIT",
                            ),
                            (
                                notifications.constants.NotificationTypes["WITHDRAW"],
                                "WITHDRAW",
                            ),
                            (
                                notifications.constants.NotificationTypes["SESSION"],
                                "SESSION",
                            ),
                        ],
                        max_length=255,
                    ),
                ),
                ("message", models.CharField(max_length=255)),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            (
                                notifications.constants.NotificationChannels["SMS"],
                                "SMS",
                            ),
                            (
                                notifications.constants.NotificationChannels["PUSH"],
                                "PUSH",
                            ),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            (
                                notifications.constants.NotificationProviders[
                                    "HOSTPINNACLESMS"
                                ],
                                "HOSTPINNACLESMS",
                            ),
                            (
                                notifications.constants.NotificationProviders[
                                    "ONESIGNAL"
                                ],
                                "ONESIGNAL",
                            ),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "receiving_party",
                    models.CharField(
                        default="All users",
                        help_text="The user id, phone number or any identification of the receiving party.",
                        max_length=255,
                    ),
                ),
                ("show_in_app", models.BooleanField(default=True)),
                ("external_response", models.JSONField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
    ]
