# Generated by Django 5.0.6 on 2024-07-17 11:57

import notifications.constants
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="phone",
        ),
        migrations.AddField(
            model_name="notification",
            name="external_response",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="receiving_party",
            field=models.CharField(
                default="All users",
                help_text="The user id, phone number or any identification of the receiving party.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    (notifications.constants.NotificationTypes["OTP"], "OTP"),
                    (
                        notifications.constants.NotificationTypes["MARKETING"],
                        "MARKETING",
                    ),
                    (notifications.constants.NotificationTypes["DEPOSIT"], "DEPOSIT"),
                    (notifications.constants.NotificationTypes["WITHDRAW"], "WITHDRAW"),
                    (notifications.constants.NotificationTypes["SESSION"], "SESSION"),
                ],
                max_length=255,
            ),
        ),
    ]
