# Generated by Django 5.0.6 on 2024-07-18 15:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0002_alter_notification_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notification",
            old_name="show_in_app",
            new_name="is_visible_in_app",
        ),
        migrations.AddField(
            model_name="notification",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
    ]
