# Generated by Django 5.0.6 on 2024-08-01 11:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0004_remove_notification_is_visible_in_app"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
