# Name of our workflow
name: Majibu Version 6 Tests


# Triggers for our workflow
on:
    # Allows you to trigger this workflow manually from Github
    workflow_dispatch:
    # Trigger workflow on push
    push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
    unit-testing:
        name: Run Unit Tests
        runs-on: ubuntu-latest
        timeout-minutes: 4

        strategy:
            matrix:
                python-version: ['3.10', '3.11']

        container:
            image: python:${{ matrix.python-version }}

        steps:
            - name: Checkout Repository Code
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
              with:
                install: true

            - name: Install Compose
              uses: cloudposse/github-action-docker-compose-test-run@main
              with:
                file: docker/docker-compose.ci.yml
                command: scripts/test.sh

            - name: Set up Docker Compose with a specific file
              run: docker compose version
