# Name of our workflow
name: Majibu Version 6 Tests


# Triggers for our workflow
on:
    # Allows you to trigger this workflow manually from Github
    workflow_dispatch:
    # Trigger workflow on push
    push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
    unit-testing:
        name: Run Unit Tests
        runs-on: ubuntu-latest
        timeout-minutes: 4

        strategy:
            matrix:
                python-version: ['3.10', '3.11']

        container:
            image: python:${{ matrix.python-version }}

        steps:
            - name: Checkout Repository Code
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              shell: bash
              run: |
                apt-get update
                apt-get install -y ca-certificates curl gnupg lsb-release
                mkdir -m 0755 -p /etc/apt/keyrings
                curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
                echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/$(lsb_release -i | awk '{ print tolower($3) }') $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list
                apt-get update
                apt-get install -y docker-ce-cli docker-buildx-plugin docker-compose-plugin


            - name: Set up Docker Compose with a specific file
              run: docker compose version
