# Name of our workflow
name: Majibu Version 6 Tests


# Triggers for our workflow
on:
    # Allows you to trigger this workflow manually from Github
    workflow_dispatch:
    # Trigger workflow on push
    push:

# Global environment variables
env:
    DEBUG: 1
    HOST_PINNACLE_USER_ID: ""
    HOST_PINNACLE_PASSWORD: ""
    HOST_PINNACLE_SENDER_ID: ""
    PAGE_SIZE: 50
    MAXIMUM_PAGE_SIZE: 100
    MPESA_BUSINESS_SHORT_CODE: ""
    MPESA_PASS_KEY: ""
    MPESA_TOKEN_URL: ""
    MPESA_STKPUSH_URL: ""
    MPESA_STKPUSH_QUERY_URL: ""
    MPESA_CONSUMER_KEY: ""
    MPESA_SECRET: ""
    MPESA_CALLBACK_URL: ""
    MPESA_B2C_SHORT_CODE: ""
    MPESA_B2C_CONSUMER_KEY: ""
    MPESA_B2C_SECRET: ""
    MPESA_B2C_URL: ""
    MPESA_B2C_PASSWORD: ""
    MPESA_B2C_INITIATOR_NAME: ""
    MPESA_B2C_QUEUE_TIMEOUT_URL: ""
    MPESA_B2C_RESULT_URL: ""
    POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
    POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
    POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
    POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
    REDIS_URL: ${{ secrets.REDIS_URL }}
    SECRET_KEY: ${{ secrets.SECRET_KEY }}
    ONESIGNAL_APP_ID: ""
    ONESIGNAL_API_KEY: ""
    WITHDRAWAL_BUFFER_PERIOD: ${{ secrets.WITHDRAWAL_BUFFER_PERIOD }}

jobs:
    unit-testing:
        name: Unit Testing
        runs-on: ubuntu-latest
        strategy:
            max-parallel: 2
            matrix:
                python-version: ['3.10']

        steps:
            - name: Checkout Repository Code
              uses: actions/checkout@v4

            - name: Set Up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v5
              with:
                python-version: ${{ matrix.python-version }}
                cache: 'pip'
                cache-dependency-path: '**/requirements*.txt'

            - name: Install Dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            - name: Start Redis
              uses: shogo82148/actions-setup-redis@v1
              with:
                redis-version: '7.2'
                auto-start: 'true'

            - name: Setup Postgres
              uses: ikalnytskyi/action-setup-postgres@v6
              with:
                username: ${{ env.POSTGRES_USER }}
                password: ${{ env.POSTGRES_PASSWORD }}
                database: ${{ env.POSTGRES_DB }}

            - name: Run Tests
              run: python manage.py test
