# Name of our workflow
name: Majibu Version 6 Tests


# Triggers for our workflow
on:
    # Allows you to trigger this workflow manually from Github
    workflow_dispatch:
    # Trigger workflow on push
    push:

# Global environment variables
env:
    DEBUG: 1
    POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
    POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
    POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
    POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
    REDIS_URL: ${{ secrets.REDIS_URL }}
    SECRET_KEY: ${{ secrets.SECRET_KEY }}
    WITHDRAWAL_BUFFER_PERIOD: ${{ secrets.WITHDRAWAL_BUFFER_PERIOD }}

jobs:
    unit-testing:
        name: Unit Testing
        runs-on: ubuntu-latest
        strategy:
            max-parallel: 4
            matrix:
                python-version: ['3.10', '3.11']

        steps:
            - name: Checkout Repository Code
              uses: actions/checkout@v4

            - name: Set Up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v5
              with:
                python-version: ${{ matrix.python-version }}
                cache: 'pip'
                cache-dependency-path: '**/requirements*.txt'

            - name: Install Dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            - name: Start Redis
              uses: shogo82148/actions-setup-redis@v1
              with:
                redis-version: '7.2'
                auto-start: 'true'

            - name: Make Script Executable
              run: chmod +x scripts/test.sh

            - name: Run Tests
              run: scripts/test.sh
